FROM openjdk:11-jre
WORKDIR /usr/src
ADD ./target/muzixapplication-0.0.1-SNAPSHOT.jar /usr/src/muzixapplication-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/usr/src/muzixapplication-0.0.1-SNAPSHOT.jar"]



